
// Register user

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@mail.com",
  "password": "12345"
}

###

// Login User

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"username": "testuser",
"password": "12345"
}

###

// Create Task

POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3ODM0MjQ3NiwiZXhwIjoxNzc4NDI4ODc2fQ._uzXrBCwiZhDnMl6I1OT-mct3dKxeczlNJYTrOSYCuI

{
  "title": "Buy Milk",
  "description": "Task one"
}

###

// Get All Tasks

GET http://localhost:8080/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3ODM0MjQ3NiwiZXhwIjoxNzc4NDI4ODc2fQ._uzXrBCwiZhDnMl6I1OT-mct3dKxeczlNJYTrOSYCuI

###

//Update Task

PUT http://localhost:8080/api/tasks/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3ODM0MjQ3NiwiZXhwIjoxNzc4NDI4ODc2fQ._uzXrBCwiZhDnMl6I1OT-mct3dKxeczlNJYTrOSYCuI

{
  "title": "Updated Buy Milk",
  "description": "Buy 3 milks"
}

###

// Delete Task

DELETE http://localhost:8080/api/tasks/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3ODM0MjQ3NiwiZXhwIjoxNzc4NDI4ODc2fQ._uzXrBCwiZhDnMl6I1OT-mct3dKxeczlNJYTrOSYCuI

###

// Complete Task

PATCH http://localhost:8080/api/tasks/8/complete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3ODM0MjQ3NiwiZXhwIjoxNzc4NDI4ODc2fQ._uzXrBCwiZhDnMl6I1OT-mct3dKxeczlNJYTrOSYCuI